services:
  app:
    build:
      dockerfile: './node/Dockerfile'
    volumes:
      - ./working:/app/working
    ports:
      - "8088:8080"
  db:
    image: mongo:latest
    volumes:
      - /data/mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    ports:
      - "27017:27017"